server {
    listen 3000;
    root /usr/share/nginx/html;
    index index.html;

    # Caching für Produktivbetrieb
    location ~* \.(js|css|png|jpg|svg|ico)$ {
        expires 7d;
        add_header Cache-Control "public";
    }

    # Alles auf index.html (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }
}
